### ISSUE TITLE
Use headings rather than HTML comments for prose.md sectioning?

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-experiment#19]
See https://github.com/mdn/stumptown-experiment/pull/14#discussion_r282563379. I can't remember now why we opted to use HTML comments rather than headings in the first place.

Unless @escattone or @Elchi3 can. I suggest we change this.

**Comment by escattone** [comment]
If I remember correctly, was it because we thought it would be easier to read, in the sense that the structure delimiters, which might have more machine-friendly rather than human-friendly names, wouldn't clutter the prose? However, I agree with the suggestion that the HTML comments should be abandoned. I like the idea of a way of providing structure within markdown files based on headings, so we have a consistent way whether we're structuring the prose or the attributes.

**Comment by wbamberg** [comment]
Having slept on it I'm starting to remember why this isn't as simple as it looks.

The most naive version, I suppose, has the prose just looking something like:

```
## Short description

Some text

## Overview

More text

## Something special

Even more text
```

The building code transforms it into something like:

```json
{
  "Short description": "<p>Some text</p>",
  "Overview": "<p>More text</p>",
  "additional_sections": [
      "<h2>Something special</h2><p>Even more text</p>"
  ]
}
```

Or perhaps the building code also transforms the section names into something more consistent and convenient for consumers:

```json
{
  "short_description": "<p>Some text</p>",
  "overview": "<p>More text</p>",
  "additional_sections": [
      "<h2>Something special</h2><p>Even more text</p>"
  ]
}
```

If it does this, then the building code needs to represent the "Short description" -> "short_description" mapping.

One thing that bothers me here is: how can the building code actually validate section names? There's no way it can tell whether "Shirt description" is a typo or an additional section.

Another thing is localisation: in the fr version of this file, authors presumably want to use the fr translation for the H2 heading text, not "Short description", but we want to access the thing-that-is-the-short-description using the same ID in all language versions of the content.

I mean, say, VSCode might want to load the en-US version or the fr version, but either way it wants to access the short description using `video.short_description`.

Yet another thing is this: for explicitly named sections like `accessibility_concerns`, should the content include the H2 heading itself or not? Well: when we're building complete MDN pages, we will want these headings, but for example someone offering accessibility information for an element in an Accessiblity Inspector will not, because the context is clear.

That suggests that perhaps the output should look more like:

```json
{
    "short_description": {
        "title": "Short description",
        "content": "<p>Some text</p>"
    },
    "overview": {
        "title": "Overview",
        "content": "<p>More text</p>"
    }
}
```

...where the property values of course contain the fr translations when using the fr build.

I don't think this applies to additional_sections, only to sections that can be extracted and displayed out of document context.

And all this suggests that the source should contain explicit identifiers:

```
<h2 id="short_description">Short description</h2>

Some text

<h2 id="overview">Overview</h2>

More text
```

or in fr:

```
<h2 id="short_description">Short description (in fr)</h2>

Some text (in fr)

<h2 id="overview">Overview (in fr)</h2>

More text (in fr)
```

(unless we used a Markdown flavour/extension that supports IDs).

Then the building code is configured with a list of the named section IDs and their corresponding text in all supported languages. It finds sections using the IDs and validates that the heading text is what it expects.

**Comment by ddbeck** [comment]
These are some good considerations, Will. A couple thoughts:

> One thing that bothers me here is: how can the building code actually validate section names? There's no way it can tell whether "Shirt description" is a typo or an additional section.

One way to handle this would be to require registering section names (or section identifiers, more on that in a sec) in the recipe (or in `meta.yaml`, for one-offs). So we could reject "Shirt description" if (and only if) it's not found in the recipe or in `meta.yaml`.

> That suggests that perhaps the output should look more like [split section title and content]

This seems right. Plus it could be helpful for translation memory. `short_description.title` could be translated once and reused everywhere in the translated JSON outputs.

> source should contain explicit identifiers

Another option is to use the English section text, slugify it, and use _that_ as the identifier, so authors don't have to provide the `id` attribute themselves. For example, `Short description` gets turned into `short_description` and it gets checked against the recipe or `meta.yaml` to figure out if it's a valid section heading. I imagine that translation tooling could also take advantage of this too (e.g., translators wouldn't re-translate a whole Markdown file; their translation target would be the JSON structure, so they wouldn't have to fuss with attributes either).

**Comment by peterbe** [comment]
I'm in favor of disconnecting the title string from the identifier. 

* It helps the anchor links short so you can get URLs like `.../video#usage` rather than `.../video#Example_and_demonstration_of_how_to_use_this`.
* Makes URLs *not* break when the titles change. Broken anchor links are a pain. It's not going to cause a `404 Page Not Found` but it's still annoying when a link used to work and then stops. 

Also, if I read the recipe and it says `- prose.short_description?` it would suck to fail on that if it keeps changing every time someone modifies the English/French title.

**Comment by wbamberg** [comment]
@ddbeck , trying to think through your proposal.

First I think this is all premised on localizers targeting the JSON, not the stumptown content. If that doesn't work we would have to think again.

*****

The JSON builder knows about two collections of prose section identifiers:

1) predefined sections: `short_description`, `overview`, `usage_notes` etc. It could get these from the recipe for, say, html-element.

2) custom sections, like ["Scripting" in the iframe page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Scripting). These could be listed in the meta.yaml for the item.

When it's building the JSON, the JSON builder goes through prose.md looking for H2 sections. When it finds them it processes them according to some hopefully simple algorithm (like, lowercasing, spaces->underscores) and checks that the result is in one or other of these collections. If it is, it adds the contents to the JSON output under the relevant key (like `prose.short_description`). If it isn't in either collection, this is an error.

*****

Writers write prose.md just using H2 names as demarcators:

```
## Short description

blah blah

## Overview 

something else

## Scripting

something special
```

This looks free-form but it isn't really: there's an implicit rule about the values these strings can have, and a requirement to declare "Scripting" and such like.

But it's certainly very readable.

*****

I think some questions are:

**Is the section heading text represented separately, or as part of the content?**

So is it like:

```
prose.short_description: "<h2>Short description</h2><p>blah blah</p>"
```

or:

```
prose.short_description: {
    "title: "Short description",
    "content: "<p>blah blah</p>"
}
```

I think I like the second better.

**Is the section heading text taken from the content or supplied by the toolchain?**

So for example, "Short Description" would match `short_description`, but what we really want in the MDN page is "Short description". This suggests to me that the section heading text should **not** be taken from prose.md, but should be supplied by the toolchain. This is a little weird for authors, who might write "Short Description" but get it silently replaced by "Short description" in the rendered page.  

**If section heading text is supplied by the toolchain, is it done in JSON building or HTML rendering?**

I think probably it's done in HTML rendering actually. This is already the place where code has to replace identifiers in the JSON with human-readable (and localizable) strings - for example, the compat table rendering will need to do this, and the live samples rendering is going to have to supply strings like "Result".

That suggests that actually the JSON looks like:

```
prose.short_description: {
    "content: "<p>blah blah</p>"
}
```

...and it's the renderer that maps `short_description` to a string.

**Comment by ddbeck** [comment]
My answers to your questions, @wbamberg:

> Is the section heading text represented separately, or as part of the content?

I agree with your answer to this. Conceptually, I see this as saying to consumers, "here's some text about this technology and here's a label for it if you need to distinguish it from other text". This handles using the content comprehensively (e.g., rendering an MDN page with everything, where you need a label to set it off from other text) and using it selectively (e.g., an accessibility helper in the Firefox dev tools).

> Is the section heading text taken from the content or supplied by the toolchain?

Part of me wants to say that this is not really a meaningful distinction because we'll have a linter that will yell at you if your section heading text is inconsistent with a registered heading (e.g., if "Short description" is the preferred form, then "Short Description" causes the build to fail). But spelling it out that way also implies that we'll have to do huge bulk updates every time the heading text changes, which sounds pointlessly tedious. Maybe the right thing is for the text to be supplied by the toolchain and use slugs in the Markdown files:

```markdown
## short-description
blah blah

## something-special
<!-- something-special is defined in some yaml file somewhere -->
blah blah
```

But this may shake out in unexpected ways when we have actual external contributors. Maybe those identifiers will be too confusing for contributors. But I'm also confident we can change this later if we decide whatever we've picked is too confusing.

> If section heading text is supplied by the toolchain, is it done in JSON building or HTML rendering?

In the JSON, absolutely. Any consumer that wants to do something with more than one prose section is going to need a label with which to distinguish one section from another. We should give it to them. For MDN specifically, having good section headings is probably one of the most important things we can do to make the content findable and useful and it seems a bit weird to divorce that text from the text itself. This also implies that we wouldn't provide translations for section labels; the HTML site builder would need to provide its own section headings _and_ process to translate those headings.

**Comment by wbamberg** [comment]
> But spelling it out that way also implies that we'll have to do huge bulk updates every time the heading text changes, which sounds pointlessly tedious. Maybe the right thing is for the text to be supplied by the toolchain and use slugs in the Markdown files:
>
>     ## short-description
>     blah blah

Well, I was thinking about this. I think realistically, unless we use something totally semantic-free in the MD file (e.g. `## osl5f1n9j`) which I don't think we want to do, then we'd always want to update all the content if we want to change heading text.

I mean if we start with "short-description" mapping to "Short description", then decide to rename that section "Fish and chips", then it will be very confusing for people to have to continue writing "short-description". Don't you think?

I do think though that having the source in GitHub make will make these kinds of updates much simpler than they are now.

So it sounds like we should try this:

* authors can use predefined headings like "Short description" or can register custom ones in meta.yaml
* in the prose, authors just use the heading text, like `## Short description`
* the stumptown code validates that text and builds JSON that represents title and content separately

I'll experiment with implementing something like this and see what it looks like :). Thank for your thoughts on this, it's very helpful to talk it over.

**Comment by ddbeck** [comment]
> I mean if we start with "short-description" mapping to "Short description", then decide to rename that section "Fish and chips", then it will be very confusing for people to have to continue writing "short-description". Don't you think?

This is a good point. Plus now I'm craving fish and chips. And I completely agree that these bulk changes will be easier in Git. Now I'm going to go review your PR. 🔀

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/stumptown-experiment/pull/41.
